### ISSUE TITLE
Released as "all-rights" license.

### ISSUE THREAD

**Issue by coderjoe** [binamov/iis-lb#4]
This example cookbook is released as all rights reserved. Was this intentional? We want to use some parts of it in a project we're working on but I don't think it's possible for us to do so under it's current license.

Is there any way it be could be changed or sub-licensed to MIT, BSD, or a similarly permissive license?

**Comment by binamov** [comment]
All of the code provided in this cookbook is free to use, reuse, refactor and profit from. If you want actual explicit words in the repo, I can submit a patch that this is released under Apache 2.0. Let me know what works for you @coderjoe

**Comment by coderjoe** [comment]
@binamov that patch would be extremely helpful. The explicit note that it is released under Apache 2.0 would allow me to follow the example. :smile:

**Comment by coderjoe** [comment]
I'm no longer using chef and no longer need this component. Closing as not planned.
